version: 2
jobs:
  run-regular:
    docker:
      - image: alpine/git:1.0.4
    steps:
      - checkout
      - run: echo "regular run"
      - run: env
  run-tags:
    docker:
      - image: alpine/git:1.0.4
    steps:
      - checkout
      - run: echo "tag run"
      - run: env

workflows:
  version: 2
  verify-dist-publish:
    jobs:
      - run-regular
      - run-tags:
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?$/
            branches:
              ignore: /.*/
